mysait/apps/articles/urls.py
from django.urls import path
from . import views

app_name = "articles"
urlpatterns = [
    path("", views.index, name = "index"),
    path("<int:article_id>", views.detail, name = "detail"),
    path("<int:article_id>/leave_comment", views.leave_comment, name = "leave_comment"),
]

mysait/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include("articles.urls")),
]

mysait/apps/articles/models.py
import datetime
from django.db import models
from django.utils import timezone

# Создаю класс Article, который отвечает за создание статьи

class Article(models.Model):
	article_title = models.CharField("Название статьи.", max_length = 200)
	article_text = models.TextField("Текст статьи.")
	pub_date = models.DateTimeField("Дата публикации.")

	# Функция которая возвращает вместо индекса статьи, её название
	def __str__(self):
		return self.article_title

	# Функция которая возвращает нам True, если статье не больше 7 дней
	def was_published_recently(self):
		return self.pub_date >= (timezone.now() - datetime.timedelta(days = 7))

	# Создаю класс Meta, который меняет название с англ на Русский
	class Meta:
		verbose_name = "Статья"
		verbose_name_plural = "Статьи"

# Создаю класс Comment, который отвечает за создание комментариев к статье

class Comment(models.Model):
	arcticle = models.ForeignKey(Article, on_delete = models.CASCADE)
	author_name = models.CharField("Имя коментатора.", max_length = 50)
	comment_text = models.CharField("Текст коментатора.", max_length = 200)

	# Функция которая возвращает вместо индекса комментария, имя его автора
	def __str__(self):
		return self.author_name

	# Создаю класс Meta, который меняет название с англ на Русский
	class Meta:
		verbose_name = "Комментарий"
		verbose_name_plural = "Комментарии"

mysait/apps/articles/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from .models import Article
from django.urls import reverse

def index(request):
	latest_articles_list = Article.objects.order_by("-pub_date")[:5]
	return render(request, "articles/list.html", {"latest_articles_list" : latest_articles_list})

def detail(request, article_id):
	try:
		a = Article.objects.get( id = article_id)
	except:
		raise Http404("Статья не найдена!")

	latest_comments_list = a.comment_set.order_by('-id')[:10]

	return render(request, 'articles/detail.html', {'article': a, 'latest_comments_list':latest_comments_list})

def leave_comment(request, article_id):
	try:
		a = Article.objects.get( id = article_id)
	except:
		raise Http404("Статья не найдена!")
	a.comment_set.create(author_name = request.POST['name'], comment_text = request.POST['text'])
	return HttpResponseRedirect( reverse("articles:detail", args = str((a.id))) )

mysait/templates/articles/detail.html
{% extends "base.html" %}

{% block title %}{{article.article_title}}{% endblock %}

{% block content %}

<center><h2>{{article.article_title}}</h2></center>	

<center><p>{{article.article_text}}</p></center>

<em>{{article.pub_date}}</em>

{% if article.was_published_recently %}
НОВАЯ СТАТЬЯ!
{% endif %}

<hr>

{% if latest_comments_list%}
	
	{% for c in latest_comments_list %}
		<p>
			<strong>{{c.author_name}}</strong>
			<p>{{c.comment_text}}</p>
		</p>
	{% endfor%}

{% else %}
Комментарии не найдены! Станьте первым!
{% endif %}

<hr>

<form action="{% url 'articles:leave_comment' article.id %}" method="POST">

	{% csrf_token %}

	<input type="text" required="" placeholder="Ваше имя" name="name"><br>
	<textarea name="text" required="" placeholder="Текст комментария" cols="30" rows="10"></textarea><br>

	<button type="supmit">Оставить комментарий</button>

</form>

{% endblock %}

mysait/templates/articles/list.html
{% extends "base.html" %}

{% block title %}Последние статьи{% endblock %}

{% block content %}

	{% if latest_articles_list %}

		{% for a in latest_articles_list %}
			<a href="{% url 'articles:detail' a.id %}">{{a.article_title}}</a>
		{% endfor %}

	{% else %}
		Статьи не найдены )=
	{% endif %}

{% endblock %}

mysait/templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="utf-8">
	<title>{% block title %}Моя страница{% endblock %}</title>
</head>
<body>
	
	{% block content %}{% endblock %}

</body>
</html>

mysait/templates/detail.html
{% extends "base.html" %}

{% block title %}{{article.article_title}}{% endblock %}

{% block content %}

	<h2>Привет</h2>	

{% endblock %}